# network
account_id: "566399633171"
shared_services_account_id: "566399633171"
regions:
  - ap-northeast-1
# すでに存在するvpcを使う場合はコメントアウトをはずしてProject名を指定する
vpc_base_project: aces-platform
cidr: 10.252.0.0/24
transit_gateway_id: tgw-02791f391dc181333
# 存在する場合はコメントアウトをはずす
open_id_connect_provider_arn: arn:aws:iam::566399633171:oidc-provider/token.actions.githubusercontent.com
sg_sagemaker_ingress_ports: []

# github repository
github_owner: aces-inc
github_repo: project-template

# docker repository
ECR_REPOSITORY: aces-platform-project-example-dev-algorithm
ECR_DEPLOY_TAG: deploy

# service
# 非同期APIで実行するAWSコンポーネント ['sagemaker', 'aws_batch'] (省略すると'aws_batch')
ASYNC_COMPONENT_SERVICE: sagemaker
MEM_PROFILE: "1"
TIME_PROFILE: "1"
# GPU_PROFILEをon("1")にすると200ms余分にかかるので本番適用は注意
GPU_PROFILE: "1"
METRICS_TOPIC_ARN: "arn:aws:sns:ap-northeast-1:566399633171:aces-platform-dev-notify-inference-results"
REQUEST_LOG_TOPIC_ARN: "arn:aws:sns:ap-northeast-1:566399633171:aces-platform-dev-notify-request-log"

## sagemaker
SAGEMAKER_DATA_PATH: /opt/ml/model
# SAGEMAKER_ENDPOINT_NAME (省略時は{Project}-{Env}-{RELEASE_VERSION})
# SAGEMAKER_ENDPOINT_NAME: aces-platform-project-example-dev-deploy
# SAGEMAKER_INSTANCE_TYPE: ml.t2.medium
SAGEMAKER_INSTANCE_TYPE: ml.t2.xlarge
# SAGEMAKER_INSTANCE_TYPE: ml.g4dn.xlarge
SAGEMAKER_INITIAL_INSTANCE_COUNT: 1
SAGEMAKER_MAX_CONCURRENCY: 1
SAGEMAKER_WEIGHT_SOURCE_S3KEY: shared/weights/deploy.tar.gz

# SAGEMAKER_SERVERLESS https://aces.kibe.la/notes/31525)
# SAGEMAKER_SERVERLESS: True
# SAGEMAKER_SERVERLESS_MAX_MB: 6144

## aws batch
AWS_BATCH_DOCKER_DATA_PATH: /opt/ml/model
SSM_PARAMETER_BATCH_JOB_DEFINITION: /dev/aces-platform-project-example/aws_batch_job_definition_arn
aws_batch_shared_memory: 4096
# large: 7168, xlarge: 14336, 2xlarge: 30720
aws_batch_memory_per_instance: 7168
#aws_batch_memory_per_instance: 14336
# aws_batch_memory_per_instance: 30720

aws_batch_max_job: 6
aws_batch_min_job: 0
# large: 2, xlarge: 4, 2xlarge: 8
aws_batch_vcpu_per_instance: 2
#aws_batch_vcpu_per_instance: 4
# aws_batch_vcpu_per_instance: 8
aws_batch_instance_type: m5.large
# aws_batch_instance_type: g4dn.xlarge
# aws_batch_instance_type: g4dn.2xlarge

## aws batch (longtime)
aws_longtime_batch_max_job: 6
aws_longtime_batch_instance_type: m5.large
# aws_longtime_batch_instance_type: g4dn.xlarge
# aws_longtime_batch_instance_type: g4dn.2xlarge
batch_trigger_s3_bucket: aces-platform-project-example-dev-batch-trigger

# monitoring
event_bus_arn: arn:aws:events:ap-northeast-1:566399633171:event-bus/aces-platform-dev-eventbridge-bus-receiver
